# Generated by Django 3.2 on 2021-04-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='loses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
